version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  fiap_hack_mediaprocessing:
    image: wstecnologia/fiap_hack_mediaprocessing
    container_name: fiap_hack_mediaprocessing
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
