version: '3.8'

services:
  fiap_hack_mediaprocessing:
    image: wstecnologia/fiap_hack_mediaprocessing
    container_name: fiap_hack_mediaprocessing
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
